### PR TITLE
Refactoring code.

### PR DESCRIPTION
**Pull request by gregberge**
- Add a "primus-rooms" adapter.
- Remove redis dependency.
- Add tests.

I have added a primus-rooms adapter, so now this module can replace primus-redis-rooms. I have refactored a little your existing code and i have added mocha for testing.

### CODE REVIEW

**Comment by gregberge** [comment]
Tests are not OK on node v0.11.x since Primus is not compatible with this version (small bug with setTimeout).

**Comment by 3rd-Eden** [comment]
@neoziro What kind of issues are you facing with Primus on 0.11?

**Comment by gregberge** [comment]
@3rd-Eden https://travis-ci.org/mmalecki/primus-redis/jobs/16879047

**Comment by gregberge** [comment]
My PR is not good, i close it. I will make a primus-redis compatible with @cayasso stack.

**Pull request closed without merging**
